manifest:
  remotes:
    - name: or-agami
      url-base: https://github.com/or-agami
  projects:
    - name: zmk
      remote: or-agami
      revision: main
      import: app/west.yml
  self:
    path: config
